version: "3.1"

services:
  #  spring-boot:
  #    build: ./
  #    mem_reservation: 512M
  #    ports:
  #      - "8080:8080"
  #    depends_on:
  #      postgres:
  #        condition: service_healthy
  #    healthcheck:
  #      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
  #      interval: 30s
  #      timeout: 10s
  #      retries: 5
  #    environment:
  #      PROFILE: prod


  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-config/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d spring" ]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:



